[package]
name = "alkif"
version = "1.0.0"
description = "ALKIF PHP site"

[dependencies]
"php/php" = "^8.2.0"

[fs]
"/app" = "."

[[command]]
name = "start"
module = "php/php"
runner = "wasi"
args = ["-S", "0.0.0.0:8080", "-t", "/app"]
